### ISSUE TITLE
kimai2 - ldap integration planned?

### ISSUE THREAD

**Issue by clyso-dr** [robjuz/helm-charts#11]
Is a LDAP integration planned for the kimai2 helm-chart?
Official documentiation: https://www.kimai.org/documentation/ldap.html

**Comment by robjuz** [comment]
Basically it should be possible. I see just one little problem. 

An additional composer package needs to be installed in the kimai2 installation. So the official image should have it installed or there user will be forced to use a custom image.

**Comment by robjuz** [comment]
@clyso-dr Please try to use the `configuration` field in `values.yaml` like this.

```
configuration: |-
  monolog:
      handlers:
          main:
              path: php://stderr
  ldap:
      activate: true
      connection:
          host: <you_ldap_host>
      user:
          baseDn: ou=users, dc=kimai, dc=org
      role:
          baseDn: ou=groups, dc=kimai, dc=org
 ```
