### ISSUE TITLE
Tokenizer problem

### ISSUE THREAD

**Issue by Fokines** [robjuz/helm-charts#125]
Hello! 
I was trying to deploy Nominatim with helm into the k8s cluster via Flux CD
Here is my values:

```
  values:
    nominatimUi:
      enabled: true
      version: 3.7.1
    extraEnvVars:
      - name: NOMINATIM_TOKENIZER
        value: "icu"
    ingress:
      enabled: true
      ingressClassName: "internal-nginx"
      hostname: nominatim.test.com
      path: /
      annotations:
        kubernetes.io/ingress.class: "internal-nginx"
        kubernetes.io/tls-acme: "true"
      tls: true
    postgresql:
      enabled: false
    externalDatabase:
      existingSecretDsn: db-nmt
      existingSecretDsnKey: POSTGRESQL_DSN
```
My DB secret is fine, I tried to log in with the same creds, the secret looks like:
`postgresql://nominatim:password@123.123.123.123:5432/nominatim`

This is the error I get:
```
2025-06-26 19:07:31: Using project directory: /nominatim
2025-06-26 19:07:31: Setting up website directory at /nominatim/website
2025-06-26 19:07:31: Tokenizer was not set up properly. Database property missing.
2025-06-26 19:07:31: FATAL: Cannot initialize tokenizer.
```
If I tried to set `initJob` to `true`, this is what I would get (see the screenshot)

![Image](https://github.com/user-attachments/assets/fe72bd61-1029-4109-9b50-5401c55f5fa5)
