### ISSUE TITLE
Bad mapping between values.yaml and mariadb?

### ISSUE THREAD

**Issue by neerdoc** [robjuz/helm-charts#2]
Vanilla installation of the helm chart now works in rancher. Ingress gets picked up with TLS and everything.

However, I did want to change all the passwords in the `values.yaml` file, and then the setup fails. It seems like there is a mismatch in the mapping of variables somehow.

When I change the two passwords for the database like this:
```
mariadb:
  architecture: standalone
  auth:
    database: kimai
    password: 'changed?Password1'
    rootPassword: 'myNewRootPass'
    username: kimai
```
The `kimai/kimai2` pod fails with the following error:
```
Testing DB:** new \PDO(mysql:host=changed?Password1;dbname=changed;port=3306, kimai, , [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (?)Checking DB: 10 
```
So, as far as I can see, it looks like the `mariadb.auth.password` variable:
1. Gets mapped to both `host` and `dbname` (and not(?) to the password)
2. In the mapping to `dbname` it also gets truncated at the questionmark.

I double checked the Secrets in kubernetes, and there the passwords are correctly stored, so it _should_ not be a problem with strange characters and/or escaping.
