### ISSUE TITLE
Could not reliably determine the server's fully qualified domain name

### ISSUE THREAD

**Issue by ferhatguneri** [robjuz/helm-charts#43]
After fresh install on kubernetes (AKS) 1.24 I've got below error in the pod. Could you please help to fix?

2023-03-16 17:36:43: Using project directory: /nominatim 2023-03-16T17:36:43.429407645Z 2023-03-16 17:36:43: Setting up website directory at /nominatim/website 2023-03-16T17:36:46.603693673Z Enabling module rewrite. 2023-03-16T17:36:46.607675973Z To activate the new configuration, you need to run: 2023-03-16T17:36:46.607694974Z service apache2 restart 2023-03-16T17:36:46.624620700Z AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.240.0.152. Set the 'ServerName' directive globally to suppress this message

Here is my installation instructions.

helm repo add robjuz https://robjuz.github.io/helm-charts/

```
cat <<EOF> nomi-values-1.yaml
nominatimInitialize:
  enabled: true
  pbfUrl: "https://download.geofabrik.de/europe/turkey-latest.osm.pbf"

postgresql:
  primary:
    persistence:
      size: 30Gi
    extendedConfiguration: |
      shared_buffers = 2GB
      maintenance_work_mem = 10GB
      autovacuum_work_mem = 2GB
      work_mem = 50MB
      effective_cache_size = 24GB
      synchronous_commit = off
      max_wal_size = 1GB
      checkpoint_timeout = 10min
      checkpoint_completion_target = 0.9
      fsync = off
      full_page_writes = off
EOF

helm upgrade --install nominatim robjuz/nominatim -n services -f nomi-values-1.yaml
```

```
cat <<EOF> nomi-values-2.yaml
nominatimUi:
  enabled: true
  version: 3.2.1
  configuration: |-
    Nominatim_Config.Nominatim_API_Endpoint = '/';

nominatimInitialize:
  enabled: false
  pbfUrl: "https://download.geofabrik.de/europe/turkey-latest.osm.pbf"

ingress:
  enabled: true
  hostname: nominatim.domain.com

postgresql:
  primary:
    persistence:
      size: 30Gi
EOF

helm upgrade --install nominatim robjuz/nominatim -n services -f nomi-values-2.yaml
```
