### ISSUE TITLE
[kimai2] configurationFromSecret specify secret name

### ISSUE THREAD

**Issue by jonasgroenke** [robjuz/helm-charts#71]
Hey, 
is it possible to add a variable for the config secret name?
Currently, it always uses the fullname of the chart.
I'm deploying the chart with flux and kustomize  and it's very complicated to specify the name for the secret because kustomize always applies a name suffix, which is totally fine for all other resources.

https://github.com/robjuz/helm-charts/blob/master/charts/kimai2/templates/deployment.yaml#L214

Something like this. If the secret name is not set, we can still use the fullname as a default for backward compatibility.
```yaml
configurationFromSecret:
    enabled: true
    secretName: myConfigSecret
```

If you want, I can also create a pull request.

Kind regards
