### ISSUE TITLE
can't login 

### ISSUE THREAD

**Issue by RLutsch** [robjuz/helm-charts#76]
I deployed using the helm chart and it's not letting me logged in, tried a few different ways and checked that the secret matches etc but no luck 

here is my values
``` 
service:
  type: ClusterIP
kimaiAdminPassword: "********"
kimaiUsername: "admin"
ingress:
  enabled: true
  pathType: ImplementationSpecific
  ingressClassName: "nginx"
  hostname: kimai.example.com
  path: /
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true
```
