### ISSUE TITLE
Let's Encrypt example

### ISSUE THREAD

**Issue by robbash** [robjuz/helm-charts#95]
Hi @robjuz.

Thanks for the Helm chart, great job! Well documented too.

I had to have a couple of attempts publishing Kimai in my cluster tho and get it to work with my custom domain and a Let's Encrypt cert. Therefore just wanted to share my `values.yaml` in case you want to add a couple of examples to the README.

```
kimaiAppSecret: "generated_secret"

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: kimai.mydomain.dev
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  type: ClusterIP

mariadb:
  enabled: false

externalDatabase:
  host: 192.168.1.60
  port: 3306
  user: kimai
  password: password
  database: kimai
```

Happy to add to your README and create a PR if you want..

Cheers
